### ISSUE TITLE
Jsplumb-ed blocks break whenever hotweb reloads the page

### ISSUE THREAD

**Issue by maxknivets** [progrium/vizgo#17]
![Screenshot from 2020-03-24 23-50-40](https://user-images.githubusercontent.com/34922382/77480447-662b0a80-6e2a-11ea-8451-0c59b5b885be.png)
This happens whenever hotweb detects a change in constructor's source files.

**Comment by progrium** [comment]
This still happening?

**Comment by maxknivets** [comment]
Doesn't seem to happen after the recent pushes. Will close this for now.
