### ISSUE TITLE
The outflow arrow doesn't disappear if its re-connected to different inflows.

### ISSUE THREAD

**Issue by maxknivets** [progrium/vizgo#19]
![Screenshot from 2020-03-25 14-55-26](https://user-images.githubusercontent.com/34922382/77538647-b648b200-6ea8-11ea-936f-4554c3488b75.png)
Steps to reproduce:
1) Connect an arrow to an inflow
2) Pull the arrow out of the connected inflow and connect it to a different inflow

**Comment by maxknivets** [comment]
The issue seems to be caused by JsPlumb not changing the class of the anchor (inflow arrow) when re-connected to other outflows.

**Comment by progrium** [comment]
I think this has been resolved, can you confirm?

**Comment by maxknivets** [comment]
Just tried replicating the bug, and it seems to have been fixed. However, I stumbled upon another bug:
![ezgif com-video-to-gif(2)](https://user-images.githubusercontent.com/34922382/83069332-62a64080-a072-11ea-91f8-8f59b68a009a.gif)
