### ISSUE TITLE
remove inflow arrow drop shadow over line

### ISSUE THREAD

**Issue by progrium** [progrium/vizgo#49]
![Screen Shot 2020-06-04 at 6 45 54 PM](https://user-images.githubusercontent.com/647/83821332-b842a480-a693-11ea-9f1d-018a9f92f2e2.png)

**Comment by maxknivets** [comment]
What causes this shadow is the [drop-shadow's](https://github.com/progrium/vizgo/blob/master/ui/com/block.jsx#L32) first value. And what's weird about this issue is that I can't see the shadow on my end.

**Comment by progrium** [comment]
You should be more specific when you say "my end". What browser? What platform? Not everybody reading would know what "my end" means.
