### ISSUE TITLE
Entrypoint is at a wrong position once a new function is made

### ISSUE THREAD

**Issue by maxknivets** [progrium/vizgo#56]
![Screenshot from 2020-06-12 19-38-56](https://user-images.githubusercontent.com/34922382/84525537-798c9a00-ace4-11ea-8dcb-fdb7879e5807.png)

**Comment by progrium** [comment]
should be fixed with recent commit 504dd0b8fb642fe7416e9f7deffcca365cde153b

**Comment by maxknivets** [comment]
Can't reproduce the bug anymore. Closing the issue for now.
